# Generated by Django 5.2.7 on 2025-10-31 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dtaAssinatura', models.DateTimeField()),
                ('dscSigla', models.CharField(max_length=5)),
                ('dscFilialInstalacao', models.CharField(max_length=50)),
                ('cod_contrato', models.CharField(max_length=10)),
                ('cod_unidade', models.CharField(max_length=10)),
                ('codtipoproduto', models.CharField(max_length=20)),
                ('qtdparada', models.IntegerField()),
                ('dta_Liberacao_local_Cliente', models.DateTimeField()),
                ('dtaEntrega_contrato', models.DateTimeField()),
                ('dt_fabr', models.DateTimeField()),
                ('dscStatusEventoUnidade', models.CharField(max_length=10)),
                ('dtaEmbarque_plan', models.DateTimeField()),
                ('dtaEmbaque_efetivacao', models.DateTimeField()),
                ('idfclassifcontrato', models.CharField(max_length=10)),
                ('dscEndereço', models.CharField(max_length=50)),
                ('dsccidade', models.CharField(max_length=50)),
                ('dscbairro', models.CharField(max_length=50)),
                ('codEvento', models.CharField(max_length=30)),
                ('dtaEvento', models.DateTimeField()),
                ('dscNomeCliente', models.CharField(max_length=100)),
                ('codreprvendas', models.CharField(max_length=100)),
                ('dscnomeobra', models.CharField(max_length=100)),
                ('idfContratoMajor', models.CharField(max_length=2)),
                ('MISCELANEAS', models.CharField(max_length=255)),
                ('HORA_Instalacao', models.DecimalField(blank=True, decimal_places=2, max_digits=2)),
                ('HORA_AJUSTE', models.DecimalField(blank=True, decimal_places=2, max_digits=2)),
                ('Total', models.DecimalField(blank=True, decimal_places=2, max_digits=2)),
                ('numFilial', models.IntegerField()),
                ('Material_Completo', models.CharField(max_length=3)),
                ('Dta_Material_completo', models.DateTimeField()),
                ('StatusFinanceiro', models.CharField(max_length=20)),
                ('LibObra', models.CharField(max_length=3)),
                ('ParcelasAtrasadas', models.IntegerField()),
                ('Frete', models.CharField(max_length=15)),
                ('StatusObra', models.CharField(max_length=15)),
                ('Situação_da_unidade', models.CharField(max_length=20)),
                ('email_Supervisor', models.CharField(max_length=60)),
                ('Contato', models.CharField(max_length=30)),
                ('Telefone1', models.CharField(max_length=30)),
                ('Telefone2', models.CharField(max_length=30)),
                ('Telefone3', models.CharField(max_length=30)),
                ('Email', models.CharField(max_length=30)),
                ('cliente', models.CharField(max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
