from django.db import models
from django.contrib import admin
from django.contrib.auth.models import User

# Create your models here.
class ServiceOrder(models.Model):
  dtaAssinatura = models.DateTimeField(auto_now_add=False)
  dscSigla = models.CharField(max_length=5)
  dscFilialInstalacao = models.CharField(max_length=50)
  cod_contrato = models.CharField(max_length=10)
  cod_unidade = models.CharField(max_length=10)
  codtipoproduto = models.CharField(max_length=20)
  qtdparada = models.IntegerField()
  dta_Liberacao_local_Cliente = models.DateTimeField(auto_now_add=False)
  dtaEntrega_contrato = models.DateTimeField(auto_now_add=False)
  dt_fabr = models.DateTimeField(auto_now_add=False)
  dscStatusEventoUnidade = models.CharField(max_length=10)
  dtaEmbarque_plan = models.DateTimeField(auto_now_add=False)
  dtaEmbaque_efetivacao = models.DateTimeField(auto_now_add=False)
  idfclassifcontrato = models.CharField(max_length=10)
  dscEndereço = models.CharField(max_length=50)
  dsccidade = models.CharField(max_length=50)
  dscbairro = models.CharField(max_length=50)
  codEvento = models.CharField(max_length=30)
  dtaEvento = models.DateTimeField(auto_now_add=False)
  dscNomeCliente = models.CharField(max_length=100)
  codreprvendas = models.CharField(max_length=100)
  dscnomeobra = models.CharField(max_length=100)
  idfContratoMajor = models.CharField(max_length=2)
  MISCELANEAS = models.CharField(max_length=255)
  HORA_Instalacao = models.DecimalField(blank=True, max_digits=2, decimal_places=2)
  HORA_AJUSTE = models.DecimalField(blank=True, max_digits=2, decimal_places=2)
  Total = models.DecimalField(blank=True, max_digits=2, decimal_places=2)
  numFilial = models.IntegerField()
  Material_Completo = models.CharField(max_length=3)
  Dta_Material_completo = models.DateTimeField(auto_now_add=False)
  StatusFinanceiro = models.CharField(max_length=20)
  LibObra = models.CharField(max_length=3)
  ParcelasAtrasadas = models.IntegerField()
  Frete = models.CharField(max_length=15)
  StatusObra = models.CharField(max_length=15)
  Situação_da_unidade = models.CharField(max_length=20)
  email_Supervisor = models.CharField(max_length=60)
  Contato = models.CharField(max_length=30)
  Telefone1 = models.CharField(max_length=30)
  Telefone2 = models.CharField(max_length=30)
  Telefone3 = models.CharField(max_length=30)
  Email = models.CharField(max_length=30)
  cliente = models.CharField(max_length=30)
  created_at = models.DateTimeField(auto_now_add=True)
  
  def __str__(self):
    return self.Material_Completo
  
admin.site.register(ServiceOrder)